version: 2.1
orbs:
  cloudformation: frameio/cloudformation@0.17.3
#  aws-ecr: circleci/aws-ecr@6.14.0
  maven: circleci/maven@1.0.3
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - run: echo 'Hello world'

workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
  publish:
    jobs:
      - cloudformation/deploy:
          stack_name: sharedid-repo
          template: cloudformation-repo.yml
          args: --parameter-overrides="RepoName=sharedid"
#        filters:
#          branches:
#            only: /master/
#  publish:
#    steps:
#      - aws-ecr/build-and-push-image:
#          dockerfile: Dockerfile
#          repo: $REPO
#  initialize:
#    steps:
#      - checkout
#      - aws-cloudformation/deploy:
#          stack-name: sharedid-qa
#          template-file-path: cloudformation-cluster.yml
#          parameter-overrides:
#            - Certificate=
#            - ServiceName=SharedIdQA
#            - Image=
#            - HealthCheckPath=/healthcheck
#            - HostedZoneName=sharedid.org
#            - Subdomain=id-qa
#            - MinContainers=1
#            - MaxContainers=1
#            - AutoScalingTargetValue=100